version: '3.1'
services:
  mysql:
    container_name: comunio-stats-db
    image: yobasystems/alpine-mariadb:10.4.17-arm32v7
    volumes:
      - db-data:/var/lib/mysql
      - /home/peter/docker-compose/init/db:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_comunio
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"

  comunio-stats-backend:
    container_name: comunio-stats-backend
    image: pkabus/comunio-stats-backend:piprod
    restart: on-failure
    depends_on: 
      - "mysql"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/db_comunio?allowPublicKeyRetrieval=true&useSSL=false
    ports:
      - "8080:8080"

  comunio-stats-frontend:
    container_name: comunio-stats-frontend
    image: pkabus/comunio-stats-frontend:piprod
    restart: on-failure
    depends_on:
      - "mysql"
      - "comunio-stats-backend"
    ports:
      - "1337:3000"

  prometheus:
    container_name: comunio-stats-prometheus
    image: prom/prometheus:v2.33.4
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    container_name: comunio-stats-grafana
    image: grafana/grafana-arm32v7-linux:6.7.6
    ports:
      - "3000:3000"
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - grafana-storage:/var/lib/grafana # saves grafana storage with dashboard customizations and user information
      - ./grafana.ini:/etc/grafana/grafana.ini # contains SMTP settings for alerts
    depends_on:
      - prometheus      

volumes:
  db-data:
  grafana-storage:

networks: 
  default: 
    external: 
      name: compose-network
